[package]
name = "sjvm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
directories = "6"
walkdir = "2.5"
bincode = "2.0"
serde = "1.0"
serde_json = "1.0"
sha256 = "1.6"
