name: it-ubuntu-sjvm

services:
  rustcli:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sjvm-it-ubuntu 
    working_dir: /app
    volumes:
      - ../tests:/app/tests
    # command: sh -c "cargo test --test e2e -- --ignored && cargo test --test e2e -- --test-threads=1"
    command: sh -c "cargo test --test e2e -- --ignored --show-output && cargo test --test e2e -- --test-threads=1 --show-output"
